// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/legal/privacy": {
    params: {};
  };
  "/legal/terms": {
    params: {};
  };
  "/legal/acceptable-use": {
    params: {};
  };
  "/legal/domain-policy": {
    params: {};
  };
  "/legal/abuse": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/domains": {
    params: {};
  };
  "/dashboard/domains/register": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/settings/account": {
    params: {};
  };
  "/dashboard/settings/contact": {
    params: {};
  };
  "/dashboard/settings/api-keys": {
    params: {};
  };
  "/api/v1/me": {
    params: {};
  };
  "/api/v1/domains/availability": {
    params: {};
  };
  "/api/v1/domains": {
    params: {};
  };
  "/api/v1/settings/contact": {
    params: {};
  };
  "/api/v1/api-keys": {
    params: {};
  };
  "/api/v1/api-keys/:keyId": {
    params: {
      "keyId": string;
    };
  };
  "/auth/signin": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/auth/verify": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/legal/privacy" | "/legal/terms" | "/legal/acceptable-use" | "/legal/domain-policy" | "/legal/abuse" | "/dashboard" | "/dashboard/domains" | "/dashboard/domains/register" | "/dashboard/settings" | "/dashboard/settings/account" | "/dashboard/settings/contact" | "/dashboard/settings/api-keys" | "/api/v1/me" | "/api/v1/domains/availability" | "/api/v1/domains" | "/api/v1/settings/contact" | "/api/v1/api-keys" | "/api/v1/api-keys/:keyId" | "/auth/signin" | "/auth/signup" | "/auth/verify";
  };
  "routes/publicLayout.tsx": {
    id: "routes/publicLayout";
    page: "/" | "/legal/privacy" | "/legal/terms" | "/legal/acceptable-use" | "/legal/domain-policy" | "/legal/abuse";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/legal/privacy.tsx": {
    id: "routes/legal/privacy";
    page: "/legal/privacy";
  };
  "routes/legal/terms.tsx": {
    id: "routes/legal/terms";
    page: "/legal/terms";
  };
  "routes/legal/acceptable-use.tsx": {
    id: "routes/legal/acceptable-use";
    page: "/legal/acceptable-use";
  };
  "routes/legal/domain-policy.tsx": {
    id: "routes/legal/domain-policy";
    page: "/legal/domain-policy";
  };
  "routes/legal/abuse.tsx": {
    id: "routes/legal/abuse";
    page: "/legal/abuse";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/domains" | "/dashboard/domains/register" | "/dashboard/settings" | "/dashboard/settings/account" | "/dashboard/settings/contact" | "/dashboard/settings/api-keys";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/dashboard/domains/index.tsx": {
    id: "routes/dashboard/domains/index";
    page: "/dashboard/domains";
  };
  "routes/dashboard/domains/register.tsx": {
    id: "routes/dashboard/domains/register";
    page: "/dashboard/domains/register";
  };
  "routes/dashboard/settings/index.tsx": {
    id: "routes/dashboard/settings/index";
    page: "/dashboard/settings";
  };
  "routes/dashboard/settings/account.tsx": {
    id: "routes/dashboard/settings/account";
    page: "/dashboard/settings/account";
  };
  "routes/dashboard/settings/contact.tsx": {
    id: "routes/dashboard/settings/contact";
    page: "/dashboard/settings/contact";
  };
  "routes/dashboard/settings/api-keys.tsx": {
    id: "routes/dashboard/settings/api-keys";
    page: "/dashboard/settings/api-keys";
  };
  "routes/api/v1/me.ts": {
    id: "routes/api/v1/me";
    page: "/api/v1/me";
  };
  "routes/api/v1/domains.availability.ts": {
    id: "routes/api/v1/domains.availability";
    page: "/api/v1/domains/availability";
  };
  "routes/api/v1/domains.ts": {
    id: "routes/api/v1/domains";
    page: "/api/v1/domains";
  };
  "routes/api/v1/settings.contact.ts": {
    id: "routes/api/v1/settings.contact";
    page: "/api/v1/settings/contact";
  };
  "routes/api/v1/api-keys.ts": {
    id: "routes/api/v1/api-keys";
    page: "/api/v1/api-keys";
  };
  "routes/api/v1/api-keys.$keyId.ts": {
    id: "routes/api/v1/api-keys.$keyId";
    page: "/api/v1/api-keys/:keyId";
  };
  "routes/authLayout.tsx": {
    id: "routes/authLayout";
    page: "/auth/signin" | "/auth/signup" | "/auth/verify";
  };
  "routes/auth/signin.tsx": {
    id: "routes/auth/signin";
    page: "/auth/signin";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/auth/signup";
  };
  "routes/auth/verify.tsx": {
    id: "routes/auth/verify";
    page: "/auth/verify";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/publicLayout": typeof import("./app/routes/publicLayout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/legal/privacy": typeof import("./app/routes/legal/privacy.tsx");
  "routes/legal/terms": typeof import("./app/routes/legal/terms.tsx");
  "routes/legal/acceptable-use": typeof import("./app/routes/legal/acceptable-use.tsx");
  "routes/legal/domain-policy": typeof import("./app/routes/legal/domain-policy.tsx");
  "routes/legal/abuse": typeof import("./app/routes/legal/abuse.tsx");
  "routes/dashboard/layout": typeof import("./app/routes/dashboard/layout.tsx");
  "routes/dashboard/index": typeof import("./app/routes/dashboard/index.tsx");
  "routes/dashboard/domains/index": typeof import("./app/routes/dashboard/domains/index.tsx");
  "routes/dashboard/domains/register": typeof import("./app/routes/dashboard/domains/register.tsx");
  "routes/dashboard/settings/index": typeof import("./app/routes/dashboard/settings/index.tsx");
  "routes/dashboard/settings/account": typeof import("./app/routes/dashboard/settings/account.tsx");
  "routes/dashboard/settings/contact": typeof import("./app/routes/dashboard/settings/contact.tsx");
  "routes/dashboard/settings/api-keys": typeof import("./app/routes/dashboard/settings/api-keys.tsx");
  "routes/api/v1/me": typeof import("./app/routes/api/v1/me.ts");
  "routes/api/v1/domains.availability": typeof import("./app/routes/api/v1/domains.availability.ts");
  "routes/api/v1/domains": typeof import("./app/routes/api/v1/domains.ts");
  "routes/api/v1/settings.contact": typeof import("./app/routes/api/v1/settings.contact.ts");
  "routes/api/v1/api-keys": typeof import("./app/routes/api/v1/api-keys.ts");
  "routes/api/v1/api-keys.$keyId": typeof import("./app/routes/api/v1/api-keys.$keyId.ts");
  "routes/authLayout": typeof import("./app/routes/authLayout.tsx");
  "routes/auth/signin": typeof import("./app/routes/auth/signin.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/auth/verify": typeof import("./app/routes/auth/verify.tsx");
};